### PR TITLE
Rename open to run

### PR DESCRIPTION
**Pull request by riyaz**
Renamed open command to run, run seems to more easy

### CODE REVIEW

**Comment by luispereira** [comment]
I'm not getting this PR, why would you just change the author name to yours?

Also, make sure the PR is compiling, or at least comment something why is failing if you are working on it...

**Comment by cesarferreira** [comment]
This is one funny PR @riyaz You just swapped my name by your name

Am I supposed to accept it?

**Comment by cesarferreira** [comment]
image

**Comment by riyaz** [comment]
Ah, my mistake, I guess this PR got updated with the wrong changes.

**Pull request closed without merging**
